//! Numeral faces a patch can choose between, and the rule that makes a pixel
//! font land 1:1 on the LEDs.
//!
//! `vesta` is the only patch using this today (card 174: the author did not
//! love its drawn numerals and asked for pixel fonts, and for the face to be
//! configurable). It is a crate-wide module rather than one of vesta's files
//! because the faces are worth having twice - "we'll probably want to use our
//! font selections in other patches" - so the API here is deliberately not
//! vesta-shaped: a face has a name, a glyph box and a scale, and answers
//! whether there is ink at a point of a glyph. Glyphs are looked up **by
//! `char`**, so a later card can cut letters or punctuation into a face
//! without touching a caller, even though only `'0'..='9'` exist today. A
//! glyph a face has not got is simply empty everywhere, which is also how
//! vesta draws its blank card.
//!
//! **The half-LED rule, which every patch will need.** The panel is a grid of
//! discrete LEDs, so a bitmap whose cells *are* LEDs is exactly crisp - every
//! lit LED at full level, every other one black - where an outline sampled
//! into the same grid is anti-aliased fuzz at every edge. That only holds if
//! the cell boundaries fall on LED boundaries, and a cell boundary is only on
//! an LED boundary if the glyph box's own corner is a whole number of LEDs
//! from wherever the patch has centred it. So a face 13 LEDs wide **cannot be
//! centred**: `x0` is -7, half an LED off centre, because a centred one would
//! put every column across two LEDs and turn the whole face to mush. The
//! generator works `x0`/`y0` out and [`Bitmap::crisp`] records whether the
//! result holds; a patch only has to place the glyph's centre on a pixel
//! boundary and draw at `size` 1.
//!
//! **Where the data comes from.** [`data`] is generated by
//! `tools/art-faces.py` from two upstream font repositories, and every face in
//! it is redistributable - see `crates/art/src/faces/FACES.md` for each one's
//! attribution and licence. The bitmaps are unmodified extracts of the digits.

pub mod data;
pub mod stroked;

pub use data::{DEFAULT, FACES, NAMES};

/// One face a `font` parameter can choose.
pub struct Face {
    /// What it is called on the page.
    pub name: &'static str,
    /// Where its shapes came from: a repository, a revision and a file, or a
    /// module of this crate for a face drawn here. `FACES.md` has the licences.
    pub source: &'static str,
    /// One line about it, for `screeny-art list` and the README.
    pub note: &'static str,
    /// The glyphs it has, in the order its data holds them.
    pub glyphs: &'static [char],
    pub ink: Ink,
}

/// How a face's ink is decided at a point.
pub enum Ink {
    /// Paths stroked with one round pen ([`stroked`]), so `weight` moves the
    /// stroke and every edge is a distance from a skeleton.
    Stroked,
    /// Cells. `weight` does nothing: the face has the weight it was cut at.
    Bits(Bitmap),
}

/// A face as cells, `scale` LEDs across each.
///
/// See the module's half-LED rule for why `x0` and `y0` are what they are.
pub struct Bitmap {
    /// Cells across and down, per glyph.
    pub w: u32,
    pub h: u32,
    /// LEDs per cell.
    pub scale: f32,
    /// The box's top-left corner, in LEDs from the glyph's centre.
    pub x0: f32,
    pub y0: f32,
    /// Whether every cell lands whole on an LED when the patch draws at 1:1.
    pub crisp: bool,
    /// `h` rows per glyph, in [`Face::glyphs`] order; bit `x` of a row is
    /// cell `x` from the left.
    pub rows: &'static [u64],
}

impl Bitmap {
    /// Is the cell under `(x, y)` - LEDs from the glyph's centre - lit?
    #[must_use]
    pub fn cell(&self, g: usize, x: f32, y: f32) -> bool {
        let (cx, cy) = (((x - self.x0) / self.scale).floor(), ((y - self.y0) / self.scale).floor());
        if cx < 0.0 || cy < 0.0 || cx >= self.w as f32 || cy >= self.h as f32 {
            return false;
        }
        let row = self.rows[g * self.h as usize + cy as usize];
        (row >> cx as u32) & 1 == 1
    }
}

impl Face {
    /// Where `ch` sits in this face's data, or `None` if it has not got it.
    #[must_use]
    pub fn index(&self, ch: char) -> Option<usize> {
        self.glyphs.iter().position(|c| *c == ch)
    }

    /// Whether a glyph drawn at 1:1 lands whole on the LEDs (see the module's
    /// half-LED rule). A stroked or outline face never does, by construction.
    #[must_use]
    pub fn crisp(&self) -> bool {
        match &self.ink {
            Ink::Stroked => false,
            Ink::Bits(b) => b.crisp,
        }
    }

    /// The box the face draws in, in LEDs, at `weight` (which only the stroked
    /// face uses). A patch sizes its slot against this.
    #[must_use]
    pub fn size(&self, weight: f32) -> (f32, f32) {
        match &self.ink {
            Ink::Stroked => (stroked::A * 2.0 + weight, stroked::B * 2.0 + weight),
            Ink::Bits(b) => (b.w as f32 * b.scale, b.h as f32 * b.scale),
        }
    }

    /// The middle of a glyph's ink, in LEDs from the box's centre, down
    /// positive - and `None` for a glyph this face has not got.
    ///
    /// A font's colon sits on its baseline, which is near the bottom of a box
    /// the digits fill, so a patch that wants the colon *between* two things
    /// rather than under them has to know where its ink actually is. Cheap
    /// enough to call once a frame; do not call it once a sample.
    ///
    /// **Rounded to a whole LED**, because this is the half-LED rule again:
    /// a patch that lifts a glyph by half an LED puts every one of its cells
    /// across two LEDs and the crispness the face was chosen for is gone.
    #[must_use]
    pub fn middle(&self, ch: char) -> Option<f32> {
        let g = self.index(ch)?;
        let Ink::Bits(b) = &self.ink else { return Some(0.0) };
        let rows = &b.rows[g * b.h as usize..][..b.h as usize];
        let first = rows.iter().position(|r| *r != 0)?;
        let last = rows.iter().rposition(|r| *r != 0)?;
        Some((b.y0 + (first + last + 1) as f32 * 0.5 * b.scale).round())
    }

    /// Is there ink at `(x, y)`, in LEDs from the glyph's centre?
    ///
    /// `weight` is the stroke width in LEDs, and only a stroked face listens
    /// to it. A glyph this face has not got is empty everywhere.
    #[must_use]
    pub fn ink(&self, ch: char, x: f32, y: f32, weight: f32) -> bool {
        let Some(g) = self.index(ch) else { return false };
        match &self.ink {
            Ink::Stroked => stroked::distance(g, x, y) <= weight * 0.5,
            Ink::Bits(b) => b.cell(g, x, y),
        }
    }

    /// Ink well inside the stroke, for reading a glyph back off a panel.
    ///
    /// A crisp bitmap has no edge to erode - an LED is lit or it is not - so
    /// its core is its ink. A stroked or outline face has a ramp, and a test
    /// that counted those pixels as ink would be testing the anti-aliasing.
    #[must_use]
    pub fn core(&self, ch: char, x: f32, y: f32, weight: f32) -> bool {
        let Some(g) = self.index(ch) else { return false };
        match &self.ink {
            Ink::Stroked => stroked::distance(g, x, y) <= weight * 0.5 - 0.4,
            Ink::Bits(b) if b.crisp => b.cell(g, x, y),
            Ink::Bits(b) => {
                const E: f32 = 0.45;
                b.cell(g, x, y) && b.cell(g, x - E, y) && b.cell(g, x + E, y) && b.cell(g, x, y - E) && b.cell(g, x, y + E)
            }
        }
    }
}

/// The face a `font` parameter's value selects.
///
/// Out of range is the default rather than a panic: a parameter is an `f32`
/// that anything may have written.
#[must_use]
pub fn face(which: f32) -> &'static Face {
    let i = if which.is_finite() { which.round().clamp(0.0, (FACES.len() - 1) as f32) as usize } else { DEFAULT as usize };
    &FACES[i]
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The page's list and the data cannot drift apart: one is generated from
    /// the other, and `choice(..)` is handed `NAMES` directly.
    #[test]
    fn the_names_are_the_faces_own_names() {
        assert_eq!(NAMES.len(), FACES.len());
        for (name, face) in NAMES.iter().zip(FACES) {
            assert_eq!(name, &face.name);
        }
        assert!((DEFAULT as usize) < FACES.len(), "the default face is not in the list");
        assert!(FACES.len() >= 4, "a choice of fewer than four faces is not a choice");
    }

    /// Every face has all ten numerals, each with ink, each inside its own
    /// box, and no two of them are the same shape.
    #[test]
    fn every_face_has_ten_distinct_numerals() {
        for face in FACES {
            let weight = 2.0;
            let (bw, bh) = face.size(weight);
            assert!(bw <= 13.5 && bh <= 22.5, "{}: {bw} x {bh} LEDs is wider or taller than a module allows", face.name);
            // Sample the box at four points per LED, which is finer than any
            // face's own cells, so two faces are compared on shape.
            let map = |ch: char| -> Vec<bool> {
                (0..(28 * 48))
                    .map(|i| {
                        let (x, y) = ((i % 28) as f32 * 0.5 - 7.0, (i / 28) as f32 * 0.5 - 12.0);
                        face.ink(ch, x, y, weight)
                    })
                    .collect()
            };
            let maps: Vec<Vec<bool>> = "0123456789".chars().map(map).collect();
            for (d, m) in maps.iter().enumerate() {
                let ink = m.iter().filter(|b| **b).count();
                assert!(ink > 40, "{}: the numeral {d} has almost no ink ({ink} samples)", face.name);
            }
            let mut worst = (usize::MAX, 0, 0);
            for a in 0..10 {
                for b in a + 1..10 {
                    let diff = maps[a].iter().zip(&maps[b]).filter(|(x, y)| x != y).count();
                    if diff < worst.0 {
                        worst = (diff, a, b);
                    }
                }
            }
            // A quarter of an LED's area is 1 sample, so 48 is twelve LEDs of
            // disagreement: the closest pair on a clock face has to differ by
            // more than a rounding.
            assert!(worst.0 >= 48, "{}: {} and {} differ in only {} samples", face.name, worst.1, worst.2, worst.0);
        }
    }

    /// A glyph a face has not got is empty, everywhere, whatever kind of face
    /// it is. This is what makes vesta's blank card work without every face
    /// having to carry a blank.
    #[test]
    fn a_glyph_a_face_has_not_got_is_empty() {
        for face in FACES {
            assert_eq!(face.index('A'), None, "{}", face.name);
            for i in -60..=60 {
                let v = i as f32 * 0.25;
                assert!(!face.ink('A', v, v, 2.0), "{}: ink at ({v}, {v}) of a glyph it has not got", face.name);
                assert!(!face.core('A', v, v, 2.0), "{}: core at ({v}, {v})", face.name);
            }
            for d in "0123456789".chars() {
                assert!(face.index(d).is_some(), "{}: no {d}", face.name);
            }
            assert!(face.glyphs.len() <= 11, "{}: an unexpected glyph", face.name);
        }
    }

    /// The colon (card 175). A face that carries one carries a real pair of
    /// marks inside its own box, and [`Face::middle`] says where they sit -
    /// which for a font colon is **below** the middle of a box the digits
    /// fill, because a colon sits on the baseline. A face without one says
    /// so, and draws nothing.
    #[test]
    fn a_face_that_carries_a_colon_carries_a_real_one() {
        let mut carried = 0;
        for face in FACES {
            let Some(mid) = face.middle(':') else {
                assert!(face.index(':').is_none(), "{}: a colon with no middle", face.name);
                continue;
            };
            carried += 1;
            let (_, bh) = face.size(2.0);
            // Two marks, not one and not a wall: ink on some rows and none on
            // the rows between them.
            let lit = |y: f32| (-8..=8).any(|i| face.ink(':', i as f32 * 0.5, y, 2.0));
            let rows: Vec<bool> = (0..(bh * 2.0) as i32).map(|k| lit(-bh * 0.5 + k as f32 * 0.5 + 0.25)).collect();
            let marks = rows.iter().enumerate().filter(|(i, on)| **on && (*i == 0 || !rows[i - 1])).count();
            assert_eq!(marks, 2, "{}: a colon of {marks} marks", face.name);
            // It sits low, as a colon does, and inside the box.
            assert!(mid > 0.0, "{}: its colon is not on the baseline ({mid})", face.name);
            assert!(mid.abs() < bh * 0.5, "{}: its colon is outside the box ({mid})", face.name);
        }
        assert!(carried >= 3, "only {carried} faces carry a colon");
    }

    /// `face` never panics and never picks something that is not a face.    /// `face` never panics and never picks something that is not a face.
    #[test]
    fn the_face_a_parameter_picks_is_always_one_of_them() {
        for v in [-1e9, -1.0, -0.4, 0.0, 0.5, 1.0, 2.4, 1e9, f32::NAN, f32::INFINITY] {
            let f = face(v);
            assert!(FACES.iter().any(|g| std::ptr::eq(g, f)), "{v} picked something else");
        }
        assert_eq!(face(0.0).name, NAMES[0]);
        assert_eq!(face(1e9).name, NAMES[NAMES.len() - 1]);
    }

    /// The half-LED rule: a crisp face's box corner is a whole number of LEDs
    /// from the glyph's centre and its cells are a whole number of LEDs
    /// across, so every cell boundary lands on an LED boundary.
    #[test]
    fn a_crisp_faces_cells_land_on_led_boundaries() {
        for face in FACES {
            let Ink::Bits(b) = &face.ink else { continue };
            if !b.crisp {
                assert!(b.scale.fract() != 0.0, "{}: not crisp but a whole LED a cell", face.name);
                continue;
            }
            assert_eq!(b.scale.fract(), 0.0, "{}: {} LEDs a cell", face.name, b.scale);
            assert_eq!(b.x0.fract(), 0.0, "{}: x0 {}", face.name, b.x0);
            assert_eq!(b.y0.fract(), 0.0, "{}: y0 {}", face.name, b.y0);
            // And the box is no more than half an LED off centre, which is as
            // close to centred as an odd width can be.
            let (bw, bh) = (b.w as f32 * b.scale, b.h as f32 * b.scale);
            assert!((b.x0 + bw * 0.5).abs() <= 0.5, "{}: {} off centre across", face.name, b.x0 + bw * 0.5);
            assert!((b.y0 + bh * 0.5).abs() <= 0.5, "{}: {} off centre down", face.name, b.y0 + bh * 0.5);
        }
    }
}
