//! sRGB8 -> panel-level lookup.
//!
//! Everything upstream of here is sRGB 8-bit (`docs/design/architecture.md`).
//! An LED driven by binary-code modulation is, to a good approximation,
//! **linear in duty cycle**: a BCM value of 32/63 emits about half the light
//! of 63/63. sRGB is not linear in light, so writing sRGB codes straight into
//! the framebuffer — which is what the bring-up spike did — makes the whole
//! ramp far too bright in the shadows and compresses the highlights into
//! nothing. That is the "mid-grey is blown out" the card is asking about.
//!
//! So the table below is the sRGB electro-optical transfer function,
//!
//! ```text
//! L = c/12.92                      for c <= 0.04045
//! L = ((c + 0.055)/1.055)^2.4      otherwise
//! ```
//!
//! evaluated at each of the 256 sRGB codes and scaled to the panel's range.
//! No float and no `powf` on the device: this is a generated constant. The
//! generator is four lines of Python and is reproduced in the doc comment on
//! [`SRGB_TO_Q`] so the table can be regenerated and checked.
//!
//! # Why the table is 16x too big
//!
//! The panel has [`LEVELS`] = 64 duty levels (6 bit-planes). Quantising the
//! EOTF to 64 levels sends **34 of the 256 sRGB codes to zero** — everything
//! below sRGB 34 emits no light at all, which is most of a dark image. So the
//! table keeps four extra fractional bits: entry `q` means "this code wants
//! `q/16` of a level".
//!
//! * Without temporal dithering the firmware uses `q >> 4` and those 34 codes
//!   are black.
//! * With it (card 030) the remainder `q & 15` is spent across successive
//!   panel refreshes, and only sRGB 0 and 1 emit nothing.
//!
//! Brightness is deliberately **not** in this table. It is output-enable duty
//! in the framebuffer (see `vendor/README.md`), so dimming the panel does not
//! move a single entry here and costs no colour depth.

/// Bit-planes per channel, and therefore duty levels: `0..=63`.
pub const PLANES: usize = 6;
pub const LEVELS: u16 = (1 << PLANES) - 1; // 63

/// Fractional bits carried below one duty level.
pub const FRAC_BITS: u16 = 4;
pub const FRAC: u16 = 1 << FRAC_BITS; // 16

/// sRGB code -> panel duty in 1/16ths of a level, i.e. `0 ..= 63*16`.
///
/// Generated by:
///
/// ```python
/// def lin(c):
///     c /= 255.0
///     return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
/// print([round(1008 * lin(s)) for s in range(256)])
/// ```
pub static SRGB_TO_Q: [u16; 256] = [
    0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, //
    5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 12, 12, 13, 14, //
    15, 15, 16, 17, 18, 19, 20, 20, 21, 22, 23, 24, 25, 26, 28, 29, //
    30, 31, 32, 33, 35, 36, 37, 39, 40, 41, 43, 44, 46, 47, 49, 50, //
    52, 53, 55, 57, 58, 60, 62, 64, 65, 67, 69, 71, 73, 75, 77, 79, //
    81, 83, 85, 87, 89, 92, 94, 96, 98, 101, 103, 105, 108, 110, 113, 115, //
    118, 120, 123, 126, 128, 131, 134, 137, 140, 142, 145, 148, 151, 154, 157, 160, //
    163, 166, 170, 173, 176, 179, 183, 186, 189, 193, 196, 200, 203, 207, 210, 214, //
    218, 221, 225, 229, 233, 236, 240, 244, 248, 252, 256, 260, 264, 268, 273, 277, //
    281, 285, 290, 294, 299, 303, 307, 312, 317, 321, 326, 330, 335, 340, 345, 349, //
    354, 359, 364, 369, 374, 379, 384, 390, 395, 400, 405, 410, 416, 421, 427, 432, //
    438, 443, 449, 454, 460, 466, 472, 477, 483, 489, 495, 501, 507, 513, 519, 525, //
    531, 538, 544, 550, 556, 563, 569, 576, 582, 589, 595, 602, 609, 615, 622, 629, //
    636, 643, 650, 657, 664, 671, 678, 685, 692, 699, 707, 714, 721, 729, 736, 744, //
    751, 759, 767, 774, 782, 790, 798, 805, 813, 821, 829, 837, 846, 854, 862, 870, //
    878, 887, 895, 903, 912, 920, 929, 938, 946, 955, 964, 972, 981, 990, 999, 1008, //
];

/// The identity mapping, for A/B tests: sRGB code straight to a duty level,
/// truncated to [`PLANES`] bits. This is what the bring-up spike effectively
/// did, and it is what "gamma off" means in the test commands.
#[inline(always)]
pub fn linear_q(srgb: u8) -> u16 {
    (srgb as u16 >> (8 - PLANES as u16)) * FRAC
}

#[inline(always)]
pub fn gamma_q(srgb: u8) -> u16 {
    SRGB_TO_Q[srgb as usize]
}

const _: () = assert!(SRGB_TO_Q[255] as u16 == LEVELS * FRAC);
const _: () = assert!(SRGB_TO_Q[0] == 0);
